### ISSUE TITLE
Game is unresponsive at boss 7

### ISSUE THREAD

**Issue by Odin-Kaze** [gameboy9/FF5Abridged#1]
In multiple occasion (3/4) When I reach the 7th boss the game become unresponsive.

The music is still playing but the ATB bar don't move and I cannot do anything.
Even the boss doesn't attack.

The only reason why I'm not sure if this happen 100% of the time it's because during the 3th tried i did in this Rando I encountered a Gilgamesh with infinite HP as the 6th boss.

**Comment by LockeColeFF** [comment]
I also just encountered a Gilgamesh with Infinite HP.  I even tried to cheat my way out of it and still couldn't win.

**Comment by gameboy9** [comment]
I think that version 1.0.1 will take care of these - as I mentioned in the notes, updates with FF5 caused the crashes in Abridged, so I had to update the CSV files accordingly.
